"use strict";

// D14/D17 沼レポート(アバター別支出内訳)のアバター名簿。
//
// **ここはデータだけのファイル。照合の規則は common.js にある。**
//
// D17 でのねらいの変更(2026-08-09 のユーザー実データ637明細で実測):
// これは「網羅する辞書」ではない。VRChat向けアバターは数万体あり毎日増えるので、
// 辞書に載っているものだけ当てにいく方式は原理的に破綻する。実際、D14の固定辞書33体では
// 金額の15.5%しか特定できず、辞書に無い「凪」は1点も拾えなかった。
//
// D17 の照合は、バリエーション名を分解したトークンを商品どうしで突き合わせ、
// 2商品以上に現れたトークンを自動でアバターのバケツにする(common.js の buildAvatarIndex)。
// 名簿に載っていないアバターも、買っていれば自動で順位表に出る。
// この名簿が受け持つのは次の3つだけで、網羅は目的にしていない。
//   1. 表記ゆれの統合 …… 「まぬか」と "manuka" を同じバケツへまとめる
//   2. 表示名 …………… バケツを日本語表記で見せる
//   3. 1商品でも採用 …… 名簿にある名前は、1商品にしか出てこなくてもバケツにする
//
// jp  … 日本語表記。バケツの表示名になる
// en  … ローマ字表記。**これが保存キー**なので後から変えない
//        (変えると `boothAvatarAssign` に保存済みの手動割り当てが迷子になる)
// alt … 追加の別表記(略記・旧つづり・P10で使っていた旧キー)。省略可
const AVATAR_MASTER = Object.freeze([
  { jp: "マヌカ", en: "manuka" },
  { jp: "しなの", en: "shinano" },
  { jp: "キプフェル", en: "kipfel" },
  { jp: "ミルティナ", en: "milltina", alt: ["miltina"] },
  { jp: "ルルネ", en: "rurune" },
  { jp: "まめひなた", en: "mamehinata" },
  { jp: "桔梗", en: "kikyo", alt: ["kikyou"] },
  { jp: "セレスティア", en: "selestia" },
  { jp: "ショコラ", en: "chocolat" },
  { jp: "しお", en: "sio" },
  { jp: "真冬", en: "mafuyu" },
  { jp: "エク", en: "eku" },
  { jp: "ミルフィ", en: "milfy", alt: ["ミルフ"] },
  { jp: "狛乃", en: "komano" },
  { jp: "マリシア", en: "marycia" },
  { jp: "カリン", en: "karin" },
  { jp: "フェリス", en: "felis" },
  { jp: "真央", en: "mao" },
  { jp: "舞夜", en: "maiya", alt: ["maya"] },
  { jp: "ルミナ", en: "lumina" },
  { jp: "ラスク", en: "rusk" },
  { jp: "ラシューシャ", en: "lasyusha" },
  { jp: "瑞希", en: "mizuki" },
  { jp: "萌", en: "moe" },
  { jp: "シフォン", en: "chiffon" },
  { jp: "ラプウィング", en: "lapwing" },
  { jp: "ラムネ", en: "ramune" },
  { jp: "墨惺", en: "bokusei" },
  { jp: "イチゴ", en: "ichigo" },
  { jp: "愛莉", en: "airi" },
  { jp: "竜胆", en: "rindou", alt: ["rindo"] },
  { jp: "斑霞", en: "hanka" },
  { jp: "彼方", en: "kanata" },
  { jp: "アルエ", en: "alue" },
  { jp: "リナシータ", en: "rinasciita" },
  { jp: "輝夜", en: "kaguya" },
  { jp: "まよ", en: "mayo" },
  { jp: "アッシュ", en: "ash" },
  { jp: "ハオラン", en: "haolan" },
  { jp: "ライム", en: "lime" },
  { jp: "うささき", en: "usasaki" },
  { jp: "プラチナ", en: "platinum" },
  { jp: "プラム", en: "plum" },
  { jp: "ナユ", en: "nayu" },
  { jp: "くうた", en: "kuuta" },
  { jp: "クマリ", en: "kumaly" },
  { jp: "ウェンディ", en: "wendy" },
  { jp: "凪", en: "nagi" },
  { jp: "フィオナ", en: "fiona" },
  { jp: "海咲", en: "misaki" },
  { jp: "ソフィナ", en: "sophina" },
  { jp: "水瀬", en: "minase" },
  { jp: "獏", en: "baku" },
  { jp: "泣夜", en: "nakiya" },
  { jp: "ゼヴ", en: "zev" },
  { jp: "華夜", en: "kaya" },
  { jp: "しらつめ", en: "shiratsume" },
  { jp: "薄荷", en: "hakka" },
  { jp: "珀杏", en: "hakua" },
  { jp: "ルシナ", en: "rushina" },
  { jp: "ルーシュカ", en: "rushka" },
  { jp: "ルーニャ", en: "runya" },
  { jp: "ルーナリット", en: "lunalitt" },
  { jp: "ぽわり", en: "powari" },
  { jp: "まるぼでぃ", en: "marubody" },
  { jp: "うるる", en: "ururu" },
  { jp: "フレーナ", en: "freina" },
  { jp: "カザリス", en: "cazalis" },
  { jp: "凪夜", en: "nagiya" },
  { jp: "ミント", en: "mint" },
  { jp: "フレア", en: "flare" },
  { jp: "ミーシェ", en: "mische" },
  { jp: "ここあ", en: "cocoa", alt: ["kokoa"] },
  { jp: "森羅", en: "shinra" },
  { jp: "MUMUS", en: "mumus" },
  { jp: "すやすやうさぎ", en: "suyasuyausagi" },
  // ここから下は D14(P10)の辞書にあった素体。当時の保存キーをそのまま en に残し、
  // 旧版で手動割り当てしたデータが名前付きのまま読めるようにしている
  { jp: "チセ", en: "chise" },
  { jp: "みなも", en: "minamo" },
  { jp: "しずく", en: "shizuku" },
  { jp: "十六夜", en: "izayoi" },
  { jp: "あのん", en: "anon" },
  { jp: "幽狐", en: "yuko", alt: ["yuuko"] },
  { jp: "グルス", en: "grus" },
  { jp: "リーファ", en: "leefa" },
  { jp: "イメリス", en: "imeris" },
  { jp: "サッチ", en: "sacchi" },
  { jp: "ルルカ", en: "ruruka" },
  // ここから下は D22 で BOOTH の公開ブラウズページ(3Dキャラクター / VRChatタグ /
  // スキ数順、2026-08-09取得)の上位300件から取り込んだもの。
  // 取り込む前に安全性のふるいを掛けてある(除外の理由は docs/improvement-plan.md の D22)。
  // en が日本語なのは「ローマ字を創作しない」ため。保存キーとしては
  // D17 の素体昇格が作る日本語のバケツ("ラビ先輩")と同じ形で問題ない
  { jp: "disaronno", en: "disaronno" },
  { jp: "emmelie", en: "emmelie" },
  { jp: "menno", en: "menno" },
  { jp: "moko", en: "moko" },
  { jp: "patoto", en: "patoto", alt: ["アヒルのpatoto"] },
  { jp: "peke", en: "peke" },
  { jp: "qunyan", en: "qunyan" },
  { jp: "raddoll", en: "raddoll", alt: ["RadDollV3"] },
  { jp: "siusiu", en: "siusiu" },
  { jp: "アウルカ", en: "aulka" },
  { jp: "アズキ", en: "アズキ" },
  { jp: "あのめあ", en: "あのめあ" },
  { jp: "あゆさ", en: "あゆさ" },
  { jp: "アルグレイ", en: "rgray" },
  { jp: "アルディナ", en: "アルディナ" },
  { jp: "いぬいぬ", en: "inuinu" },
  { jp: "イリオ", en: "イリオ" },
  { jp: "ウズルハ", en: "uzuruha" },
  { jp: "ウルキ", en: "uruki" },
  { jp: "ウルフェリア", en: "ウルフェリア" },
  { jp: "エルシオン", en: "エルシオン" },
  { jp: "おまねこ", en: "おまねこ" },
  { jp: "カプリィナ", en: "caprilina" },
  { jp: "カルキア", en: "carukia" },
  { jp: "カルネ", en: "kalne" },
  { jp: "かろうじてねこ", en: "かろうじてねこ" },
  { jp: "キシャ", en: "キシャ" },
  { jp: "キッシュ", en: "キッシュ" },
  { jp: "ギモザード", en: "ギモザード" },
  { jp: "きゃろん", en: "kyalong" },
  { jp: "キリサメ", en: "キリサメ" },
  { jp: "キリセ", en: "kirise" },
  { jp: "くろなつ", en: "くろなつ" },
  { jp: "くろにゃむ", en: "kuronyam" },
  { jp: "コマネ", en: "komane" },
  { jp: "コロネ", en: "コロネ" },
  { jp: "サナティア", en: "sanatia" },
  { jp: "サバラム", en: "savarum" },
  { jp: "サフィー", en: "sapphy" },
  { jp: "シアノス", en: "シアノス", alt: ["ドラゴニュート・シアノス"] },
  { jp: "シェーナ", en: "shayna" },
  { jp: "ジェラス", en: "gelas" },
  { jp: "ししゅか", en: "siska" },
  { jp: "シノノメ", en: "シノノメ" },
  { jp: "シピルカ", en: "shipilka" },
  { jp: "シャミ", en: "shami" },
  { jp: "しゅあん", en: "shuan" },
  { jp: "シュティーア", en: "stier" },
  { jp: "しゅり", en: "shri" },
  { jp: "シロモジ", en: "シロモジ", alt: ["クロモジ"] },
  { jp: "スヴァルトリリヤ", en: "スヴァルトリリヤ" },
  { jp: "すずはな", en: "suzuhana" },
  { jp: "スノーハヴォック", en: "スノーハヴォック" },
  { jp: "セフィラ", en: "sephira" },
  { jp: "セレアーテ", en: "セレアーテ" },
  { jp: "ゾーイ", en: "ゾーイ", alt: ["ボルゾイのゾーイ"] },
  { jp: "ソラハ", en: "ソラハ" },
  { jp: "ソルシエル", en: "solciel" },
  { jp: "ダージェリン", en: "darjelling" },
  { jp: "ちまこぞく", en: "chimaco" },
  { jp: "つみれ", en: "tsumire" },
  { jp: "ティコ", en: "tycho" },
  { jp: "てっさくちゃん", en: "てっさくちゃん" },
  { jp: "デルタフレア", en: "デルタフレア" },
  { jp: "てんちる", en: "tenchill" },
  { jp: "トネール", en: "トネール" },
  { jp: "とらお", en: "torao" },
  { jp: "トラス", en: "トラス", alt: ["ウェッジ"] },
  { jp: "ナナセ・ノワール", en: "nanase noir" },
  { jp: "なのでび", en: "nanodevi" },
  { jp: "ニクス", en: "ニクス" },
  { jp: "にゃにゃまる", en: "にゃにゃまる" },
  { jp: "ヌタチ", en: "ヌタチ" },
  { jp: "ヌノスプ", en: "nunosp" },
  { jp: "ネコチヤン", en: "ネコチヤン" },
  { jp: "ネミア", en: "nenmir" },
  { jp: "ノーチカ", en: "nochica" },
  { jp: "ぱたにゃこ", en: "patanyako" },
  { jp: "ひかるん", en: "hikarun" },
  { jp: "ひきくまりのクマリ", en: "ひきくまりのクマリ" },
  { jp: "びしょぬれのしずくさん", en: "びしょぬれのしずくさん" },
  { jp: "ビナア", en: "binah" },
  { jp: "ふぁふぁ", en: "ふぁふぁ" },
  { jp: "フィユエ", en: "fyuett" },
  { jp: "フォシュニア", en: "フォシュニア" },
  { jp: "フラクチュア", en: "fluctua" },
  { jp: "ベルセリナ", en: "ベルセリナ", alt: ["デビルウエイトレス ベルセリナ"] },
  { jp: "ペルラ", en: "perula" },
  { jp: "ぽちまる", en: "pochimaru" },
  { jp: "ホノカ", en: "honoka" },
  { jp: "ぽまえ", en: "ぽまえ", alt: ["インターネットのぽまえ"] },
  { jp: "ほむら", en: "ほむら" },
  { jp: "ぽんとちゅね", en: "ぽんとちゅね" },
  { jp: "ましゅ", en: "mashu" },
  { jp: "ましゅめろ", en: "ましゅめろ" },
  { jp: "まりえる", en: "まりえる" },
  { jp: "まるまるねこちゃん", en: "まるまるねこちゃん" },
  { jp: "まろまげ", en: "maromage" },
  { jp: "みなほし", en: "minahoshi" },
  { jp: "みみのこ", en: "みみのこ" },
  { jp: "ミュオン", en: "ミュオン" },
  { jp: "ミュリシア", en: "mulicia" },
  { jp: "みるくらて", en: "みるくらて", alt: ["しゅがーらて"] },
  { jp: "ムルル", en: "mururu" },
  { jp: "むろむ", en: "むろむ" },
  { jp: "むんき", en: "munkki" },
  { jp: "めいゆん", en: "meiyun" },
  { jp: "メディカルセンタースタッフさん", en: "メディカルセンタースタッフさん" },
  { jp: "メリノ", en: "メリノ" },
  { jp: "メロトロン", en: "メロトロン", alt: ["かんぺきメイドメロトロン"] },
  { jp: "モフィラ", en: "mophira" },
  { jp: "モルフォ", en: "モルフォ" },
  { jp: "ゆうぎり", en: "ゆうぎり" },
  { jp: "ヨール", en: "yawl" },
  { jp: "リーサルフリート", en: "リーサルフリート" },
  { jp: "リーメ", en: "leeme", alt: ["リーバ", "reeva"] },
  { jp: "リュオン", en: "ryuon" },
  { jp: "リュミィ", en: "ryumii" },
  { jp: "りりか", en: "りりか" },
  { jp: "リルモワ", en: "liloumois" },
  { jp: "リルル", en: "riruru" },
  { jp: "リルレオ", en: "lilleo" },
  { jp: "リンネ", en: "linne" },
  { jp: "ルイフォス", en: "lyphos" },
  { jp: "ルギネア", en: "ruginea" },
  { jp: "ルシフェ", en: "ルシフェ" },
  { jp: "ルゼブル", en: "ルゼブル" },
  { jp: "ルチカ", en: "luchika" },
  { jp: "ルフィナ", en: "rufina" },
  { jp: "ルメラナ", en: "lumelana" },
  { jp: "ルリエ", en: "lurie" },
  { jp: "ルルリア", en: "luruleah" },
  { jp: "レイニィ", en: "レイニィ" },
  { jp: "レティニア", en: "レティニア", alt: ["レティニエッタ"] },
  { jp: "ロコナ", en: "rokona" },
  { jp: "ロポリこん", en: "ロポリこん" },
  { jp: "凪夜瑠璃", en: "nagiya ruri" },
  { jp: "猫山苗", en: "猫山苗" },
  { jp: "白雪天使", en: "白雪天使" },
]);

// 「1つの素体だけの商品ではない」ことを名乗る表記。これが入っていれば、
// 素体名が1つしか読み取れなくても「複数対応」として扱う
// (Full Pack は複数素体ぶんをまとめた商品なので、1体の支出として数えると偏る)
const AVATAR_MULTI_MARKERS = Object.freeze([
  "full pack",
  "fullpack",
  "full set",
  "フルパック",
  "フルセット",
  "全対応",
  "全アバター",
  "複数アバター",
  "多対応",
  "複数対応",
]);

// D22 既知商品の辞書。品名の語彙だけでは行き先を決められない固有名を名指しで拾う。
//
// **ここもデータだけ。**照合は common.js の itemMasterSlot が行い、
// NFKC正規化+小文字化した品名本体への部分一致で当てる(語彙判定より先に見る)。
//
// match … 品名本体に含まれていれば当たる文字列。小文字で書く
//         (「もちふぃった」のように表記ゆれがある商品は、共通する部分だけを書く)
// key … 行き先。common.js の予約キーと同じ文字列。**保存キーなので後から変えない**
//       ("__multi__" / "__multi_tool__" / "__world__" / "__world_item__")
//
// 数百件へ増やす前提の並び。索引は作らず、上から順に見るだけにしてある
// (数百件×数百明細でも一瞬で終わる。遅くなってから索引を考える)
const ITEM_MASTER = Object.freeze([
  { match: "もちふぃった", key: "__multi_tool__" },
  { match: "bonesync", key: "__multi_tool__" },
  { match: "weightsync", key: "__multi_tool__" },
  { match: "meshsync", key: "__multi_tool__" },
  // 「polka」単独では音楽やポルカドット柄の商品に当たるので、商品名まで書く
  { match: "portable light kit", key: "__multi_tool__" },
]);

// D22 既知商品(完全一致)。ITEM_MASTER と違い、NFKC正規化+小文字化した品名本体との
// **完全一致**でしか当たらない。大量に並べても誤爆しないのはこのため
// (部分一致で1000件並べると、短い品名が長い品名の一部に当たって総崩れになる)。
//
// 出典: BOOTH の公開ブラウズページ(VRChatタグ / スキ数順、2026-08-09取得)。
// 3D衣装・3D装飾品・3D小道具 → __multi__、3Dツール・システム / 3Dテクスチャ /
// 3Dモーション・アニメーション → __multi_tool__、3D環境・ワールド → __world__。
//
// **これは分類の最後の砦であって上書きではない。**特定アバターや種別が先に当たる
// 商品は従来どおりそちらが勝つ(common.js の呼び出し位置は変えていない)。
const ITEM_MASTER_EXACT = Object.freeze({
  __multi__: Object.freeze([
    "Hoodie set(23アバター対応)",
    "Urban Tech Obsidian",
    "2025年第２弾『第七特務機関ワルキューレ』Seventh Special Operations Agency \"Valkyrie\"",
    "🐉DOBUITA STYLE 【for Woman】スカジャン 🐅",
    "[16Avatars]𝑵𝒐𝒊𝒓_𝑳𝒖𝒙𝒆",
    "【PB対応】【VRChat用】アクセサリー イヤリング",
    "【11アバター対応】✨Sol Paraiso✨ #VirtualCasual",
    "🐰🐰8月2日はバニーの日🐰2025年第1弾『断罪バニー - Danzai Bunny -』🐰🎁セール中🎁",
    "🩷本命ニット🩷【22アバター対応】",
    "♞C1 EXPANSION BIG SILHOUETTE MA1 & HOODIE SET♞",
    "ShadowLily【17アバター対応】",
    "【21アバター対応】 Classical chic",
    "𝐸𝑣𝑒𝑟𝐴𝑓𝑡𝑒𝑟【22アバター対応】",
    "Sailor Maiden",
    "🩷『Lop Ear Mine』ロップイヤーマイン🩷【23アバター対応】",
    "2024年第1弾『断罪セーラー』Danzai Sailor 💜",
    "でびでびぱーかー",
    "【複数アバター対応 3D衣装】ミッドナイトスクール / MIDNIGHT SCHOOL",
    "🔧HYPER TECH EVO -IGNITE-🔧",
    "✟ギミック付き衣装✟グリモワール✟15avatar対応✟",
    "VRChat向け　8bitサングラス",
    "18アバター対応  ⛩️月狐の眼⛩️",
    "【 𝙁𝙪𝙣𝙠𝙮 𝙎𝙩𝙧𝙚𝙚𝙩 𝙑𝙞𝙫𝙚 】",
    "【20アバター対応】𝙈𝙤𝙧𝙗𝙞𝙙𝘼𝙣𝙜𝙚𝙡",
    "Loose Punk (for Female avatars)  #3BON",
    "🦊Midnight Fox 2.0 🦊【髪型付き衣装 / 19アバター対応】",
    "✨【18アバター対応／50%OFF】Meira｜Lumina対応＆前面PBアップデート✨",
    "Midnight Reverie",
    "【15アバター対応】ナイト・イン・ヨシワラ - Night in Yoshiwara【MA対応】",
    "複数アバター対応 麗猫メイド  Victorian Whiskers Maid 猫セット付  #MURASAKIYA",
    "【14アバター対応】Arcane Attire【VRChat】",
    "Precious School Uniforms",
    "【16アバター対応】✨Noble_Nexus✨",
    "【Deorart モデル No.1リメイク】パンク系振袖パーカー・サルエルパンツコーデセット＆とろとろねこNECOLA #BLUESTELLA",
    "✩˚ ｡ Hollow ｡˚✩ 【25 アバター対応】",
    "✧･ﾟ•.MIRUKURU.+:｡:✧   - CREPSCOLO - クレプスコーロ🤍",
    "【13アバター対応】☃️Winter_Glow☃️",
    "🌃【VRC 衣装】Urban Grace - City",
    "【無料】Gothic Doll【キプフェル対応】",
    "👑 SALE【22アバター対応】👑『ATTITUDE : The Royal Bunny』🐰#Libero_Boutique",
    "2024年第4弾『断罪チャイナ- 罪と罰-』Danzai China Dress💜",
    "[FREE] MellowHeart Dream [PB][8 Avatar]",
    "🦇『NIGHTMARE - ナイトメア -』EXTENSION CLOTHING",
    "【セミ対応衣装】ショコラドレス Ver2.0.0【3D衣装】",
    "【Free/無料衣装】Silent Twilight【9avatar】",
    "EveningGlow【21アバター対応】",
    "2024年第8弾『断罪シスター - Danzai Sister - 』✝",
    "[31 Avatar] NOXTA",
    "2024年第5弾『YUKATA 祭囃子 - Matsuribayashi - 』",
    "♥37アバター対応♥ at2am. 【MA対応】",
    "2024年第2弾『御奉仕メイド』Gohousi Maid 💜",
    "Cipher Cloak-『サイパークロック』【16アバター対応】",
    "[21Avatars]🌐Chromium🌌",
    "【無料】Milsy-ミルシィー-【二周年記念】",
    "「StarryBlues」スターリー・ブルース　（複数アバター対応）",
    "『ベルベット・グレイス』 ‐ Velvet Grace【25アバター対応】",
    "タクティカルメイド (Tactical maid)",
    "ENDLESS",
    "🐾🎀【19アバター対応】 Esmera 🎀🐾",
    "あめショートヘア",
    "【 Double Jacket Outfit】",
    "【複数アバター対応】宵",
    "【40アバター対応】【YMファンメイド】♰LoungeWear♰",
    "『無料』天使チョーカー",
    "【7アバター対応】✨Lottie✨Voyage出展衣装",
    "【15アバター対応】TrackChina【VRChat向け衣装モデル】",
    "🩶🖤 小悪魔セーラー / 38アバター対応 🖤🩶",
    "【10000 follow thx】10000horn【free】",
    "🎉KAGUYA Update🎉【PB】『Common Days』【23 Avatars】",
    "✨HB_shop✨『13アバター対応』【3D衣装モデル】UrbisVortex",
    "【3D】Chill out wear (森羅/しなの/愛莉/マヌカ/ラシューシャ/Lapwing/Sio/水瀬/狛乃/斑霞/ミルティナ/ルルネ/Alué/Mayo/海咲対応) #LAYON服 ＃LAYONコーデ",
    "【15アバター対応】OATH JACKETコーデセット/OATH JACKET",
    "2024年第7弾『変身！まじかる☆ステッキ』- Hensin Magical Stick - 💜",
    "「ΔrtemisSailor - grace -」アルテミスセーラー - グレイス - (複数アバター対応)",
    "【16アバター対応】Prologue【VRChat向け衣装モデル】",
    "[VRC] 10アバター対応  [ Z9_1st anniversary gift ]",
    "3rd PINK♡PUDDING",
    "🐉DOBUITA STYLE 【for men】スカジャン 🐅",
    "【15アバター対応】ルミナス・デシート - LuminAs Deceit -【MA対応】",
    "【20アバター対応】487+Style Stockings  持続更新!!!",
    "[FREE] Classic Sailor Vol.1 [4 Avatar] [PB]",
    "✨HB_shop✨ アンチェイン （Unchain)",
    "🖤【15アバター対応】Lilith Vice🖤",
    "【12アバター対応】スクールエレガン　/　SCHOOL ELEGAN",
    "『Subwave』サブウェイブ【26アバター対応】",
    "🌕 《FREE》 【6アバター対応】 VelvetMoon 🌌",
    "bravado【VRChat】",
    "🤍💉ピンキーナース💉🤍15Avatar対応",
    "オリジナル3D衣装「メイガスバニー」",
    "【VRC想定】冠　シェーダーアニメーション付き",
    "🐉Agent D🐉【髪型付き衣装 / 15アバター対応】",
    "🌸Crimson Rumor🌸【髪型付き衣装 / 19アバター対応】",
    "🖤Dolly Nightmare🖤 【まめふれんず対応衣装】",
    "𝙎𝙮𝙯𝙮𝙜𝙮【22アバター対応･VRChat向け3Dモデル】",
    "GrayWhim【VRChat向け衣装】",
    "『シック・グレイス』 ‐ Chic Grace【25アバター対応】",
    "🏵️Le Hana🏵️【髪型付き衣装 / 15アバター対応】",
    "【複数アバター対応】Cultist【VRChat想定】",
    "【26アバター対応】 キロ Kyro Neko Hoodie🐈︎",
    "【15アバター対応】Rain Bouquet【VRChat】",
    "LUNALICE【22アバター対応】",
    "【54アバター対応】ストレイキングキャット #strayKingCat",
    "バイカラーブラウス＆アシメスカートセット",
    "【15アバター対応】WiccaMaid【VRChat】",
    "【19アバター対応】🏖️☀️ Mari Velle ☀️🏖️",
    "【複数アバター対応 3D衣装】マグノリア　/　MAGNOLIA",
    "✧･ﾟ•.MIRUKURU.+:｡:✧ - MELODIA - メロディア🤍",
    "巫桜(26アバター対応)",
    "「Moonlight Classic」ムーンライト・クラシック　（複数アバター対応）",
    "🎀【VRC 衣装】Melty Doll - Gothic",
    "Fairy Twin - フェアリーツイン-【PB対応】",
    "【16 アバター対応】🐇Rabbit Catch you🐇",
    "2025年第4弾『断罪ナース💉 - Danzai Nurse -』",
    "🗡Silver Inquisition🗡【16アバター対応】",
    "🎉Sale🎉【18 avatars】🧢STRYDE",
    "2024年第9弾『BISQUE DOLL - ビスクドール - 』ギミック付きドール衣装💜14アバター対応",
    "【13Avatars】夜の散歩 Nocturnal Stroll",
    "【282アバター対応】Classical Maid",
    "Chrome Decay (for Female avatar)  #3BON",
    "♥FREE♥10アバター対応♥Melty Calling♥",
    "🖤【16アバター対応】Lunabelle🖤",
    "3Dモデル「ButterflyGL」カラバリ有り 単色版有り",
    "【8アバター対応】Daily Punk",
    "【14アバター対応】フユカノHuyukano",
    "【69アバター対応】 アルティメットショーツ / Ultimate shorts",
    "🎧【VRC 衣装】Stereo Punk - Crush",
    "【6アバター対応】Polaris",
    "[30 Avatar] ANTRIX",
    "🤎Classis〖15アバター対応〗🤎",
    "PSYKHE【22アバター対応】",
    "🦋Azure Virtue🦋【15アバター対応】",
    "【複数アバター対応】Re:Bone【VRChat想定】",
    "2026年第3弾『放課後ディストーション』🌇2026年6月5日19時半発売予定！！！",
    "〈17アバター対応〉 ✦｡🐉Astel-hair｡✦",
    "2024年第11弾『SERAPHIM - セラフィム - 』12月13日販売開始💜",
    "SummerGrace【30アバター対応】",
    "【VRC想定衣装】「ArtemisSailor」アルテミス・セーラー　（複数アバター対応）",
    "💗お給仕メイド＆オリジナルシャンパンギミック💗16Avatar対応",
    "「PHANTOM VENUS」ファントム・ヴィーナス　（複数アバター対応）",
    "🌸2025年第5弾『幻影和装 - 月華ノ蛇艶 🐍🌕』 Genei Waso - Gekka no Jaen",
    "【キプフェル専用】 ♡ 𝐆𝐚𝐫𝐧𝐞𝐭 ♡ 【VRChat向け衣装+ヘアモデル】",
    "【16アバター対応】⚙️Steel Snowflake『SSF』❄️ #Libero_Boutique",
    "Snowdrop【17アバター対応】",
    "Velvet Curse Dress【18アバター対応】",
    "2025年第3弾『THE LAVIEL ARCHIVES - ラヴィエル家の静謐』🫖",
    "【13アバター対応】Lunette-ルネット-",
    "【13アバター対応】😈Devil Hex🖤 #Libero_Boutique",
    "【18 avatars】💖Night_In🌙",
    "汎用01_アレンジにゃんこ(90アバター対応)",
    "【101アバター対応】シュガーワンピ",
    "VRChat向けアクセサリー　指輪",
    "⛈ 𝗧𝘆𝗽𝗲𝟯 / RINMKR(ﾚｲﾝﾒｲｶｰ) ⛈",
    "V4N2【14アバター対応】",
    "【✨特別価格✨】ゆめかわ×病みかわアクセセット【複数アバター対応】",
    "✧･ﾟ•.MIRUKURU.+:｡:✧ - ARIETTA - アリエッタ🤍",
    "♥FREE♥8アバター対応♥Pom Pom Kiss♥",
    "🎉KAGUYA Update🎉【PB】『URGF』【23 Avatars】",
    "Urban Tech Riptide",
    "✨【VRC 衣装】STREET CHIC - FLOW",
    "【衣装】Klorfi【16アバター対応】",
    "【18 avatars】👻BOO🖤",
    "【16アバター対応】Amaryllis【VRChat向け衣装モデル】",
    "✠漆黒セレナーデ✠棺移動ギミック付き【17Avatar対応】",
    "Reveraglow【15アバター対応】",
    "Gothic Over knee boots",
    "🎀おとめ浴衣🎀【25アバター対応】",
    "👾ルーズゲーマー👾(↑→LooseGamer↓←)24アバター対応",
    "✨HB_shop✨ラスティー『rusty』",
    "【無料アイテム】3000フォロワー記念★",
    "My Sunny Femme",
    "[18Avatars]🌸Yoruhime🌸",
    "[City Chic] - 桔梗 Kikyo, セレスティア Selestia, 萌 Moe, マヌカ Manuka, 愛莉 Airi, しなの Shinano",
    "🀄Midnight Hug🀄【髪型付き衣装 / 17アバター対応】",
    "♥FREE♥6アバター対応♥Lovely pearl♥",
    "🖤(50%OFF)🖤 Temptress Saint 【17アバター対応】",
    "【VRC想定】MY CRUSH Short wolf hair",
    "【18アバター対応】 𝐋𝐕.𝟕 Cheeky_Tweaky 👙",
    "Jelly fish (ペット）",
    "[FREE] - SimpleDrawers - #REIMEISTORE",
    "【複数アバター対応衣装】Cross Memoria",
    "【100アバター以上対応】HoroNail【VRネイルチップ】【MDollnail対応】#あんらぼぶい",
    "無料！フォロワー300人記念『でっかいリボン！』VRChat",
    "【Free】無料 Maria Lace Veil #MURASAKIYA",
    "【VRC 想定】ゆるゆる天使セット ver1.00",
    "シンプルジェルネイル - Simple Gel Nail -【54アバター対応】",
    "【20アバター対応】Assault Hand【VRChat】",
    "Thx 1st ear and tail 【VRChat】",
    "漆黒の魔角 & Dark Horn😈【3Dモデル For VRChat】ver_1.03",
    "†Lost Bind†   ボディピアス (全アバター)",
    "夏休みセール！【MA対応】クラゲに変形するアクセサリーセット「タマクラゲ」(VRChat想定)",
    "動く！ PixelBoot ヘアアクセサリー (+なで警告ギミック)",
    "【VRC想定】初心者改変セット2026 / Beginner's Set 2026",
    "【無料】フォロワー2000人記念　エクリプスヘイロー",
    "パンクな猫耳キャスケットv4（PhysBone設定済み・テクスチャ差分7色）",
    "【無料】あくませっと",
    "【無料】シンプルリング【20点】",
    "動く＆掴める 球体関節多腕パーツ【3Dアクセサリー】",
    "【Free/無料】MellowRibbon【Renewal】",
    "【無料】羽と輪っか Angel Set【まめふれんず対応】",
    "【かんたん着用】DarkNailSelection【VRネイルチップ】【MDollnail対応】#あんらぼぶい",
    "【Nail&Ring】MERODROPS-もっと、近くへ-【30アバター対応】 #MEMEROLAND",
    "OblivionChoker-V2 チョーカー",
    "【無料】 SASOU_Earring",
    "Chocolate rice Nail (No.1)",
    "束縛アイマスク -Vined EyeMask-",
    "【無料】RuinHalo ヘイロー (アニメーション&パーティクル付)",
    "ANEレイヤーウルフ",
    "クロスチェーンアンダーリムメガネ&丸眼鏡v5（PhysBone設定済み・調整用ボーン入り）",
    "【無料/Free】サブカルロングネイル【16アバター対応】",
    "【VRC想定】リフレクトレンズ / Reflect Lens",
    "Stardust  Whispers  (目元パーティクル＆ボディシール)",
    "【VRC想定】アフターグロウ / Afterglow",
    "【Free】LAYON 2nd Anniversary GIFT Watch",
    "🧸Hug me Bear ⋱10k Followers Anniversary Goods⋰ For Kumachama Gimmick Update!",
    "Tangledhorn【VRChat】",
    "【無料 / VRC想定】- NightFall -",
    "【  Wing & Halo /  moe eyes  】",
    "もふもふ”狐”プフェルちゃん/Fluffy\"FOX\"pfel【ModularAvatar対応】",
    "【無料3Dモデル】チェーンなチョーカー",
    "【無料ෆフォロワー3000人記念】Fluffear Charm",
    "【VRChat想定】花水槽の飾りモノ -Herbarium Acc-【PB対応】",
    "キャンプ気分！７種類のアバターテントセット＋２種類の焚火セット",
    "E-PULSE ヘアアクセサリー",
    "【オリジナル3Dモデル】Death Arcane - デスアーケイン -【鎌】VRChat想定 パーティクルやギミック付き",
    "「TwinkleTulleRibbon」#なっふな堂",
    "『IV halo』【VRChat】",
    "夏休みセール！【MA対応】球体変形メカ「カニタマ」追従ペットギミック(VRChat想定)",
    "【4アバター対応】muffmuff❄︎snow【VRChat】",
    "FREE ぷるぷるぷりん",
    "【無料/Free】 Nekomata Ears & Tail",
    "Nidhogg Skeleton[15 Avatars] MA対応！！！",
    "【40アバター対応】Aquaglass-アクアグラス-",
    "オーディオヘアクリップ【VRChat用】",
    "【動く】狐面幻燈 - 夏夜イメージアイテムセット【VRChat向け】",
    "✨6アバター対応✨  ⛩️ Shrine Fox 🦊",
    "◤◢自主規制◤◢ギミック🚫【ModularAvatar対応】",
    "vine leg - 3D",
    "【オリジナル3Dモデル】Stella_Halo【ヘイロー】",
    "【無料】 掴めるおしゃぶり【全アバター対応】",
    "【無料】丸メガネ＆サングラス KI_Glasses【MA】",
    "🦇🖤Gothic Accessory Set🖤🕯️",
    "【FREE】サテン＆オーガンジーリボン/ふわふわに動くPB設定済み",
    "【Free/無料】Usagotchi【PB対応】",
    "GothicHeadDress 2.0+",
    "ポニフェルテ Ponyfelta【HairStyle/キプフェル専用/VRChat想定】",
    "【複数対応】揺れるピアスセット【リップシンク対応】",
    "Idol Inear Mic [28 Avatars]",
    "【thx3000followers】Aether Ribbon Cap - リボンキャップ【VRChat向け】",
    "！！SALE~8.31 ！！ 💗【FREE/無料】Manuka100Type❥動くまばたきFace&PoseAnimations ⌖ ݁˚",
    "StarCharm Lace Eyepatch / スターチャームレースアイパッチ (A7)",
    "【🎄𝐅𝐫𝐞𝐞_無料🎄】 𝐋𝐕.𝟐+ LVitamin 🍋",
    "†Stellar Bind†  チェーンリング",
    "(Free)Comet Halo&Horns",
    "【無料】Herb Horn",
    "【🌟アバター対応追加記念SALE🌟】✧StarChain✧【VRChat向けピアス】",
    "レースアップリボン for Hakanage Lowpony【3Dアクセサリー】",
    "瞬く瞳のヘイロー【VRChat想定】【MA対応】",
    "【パーティクルを展開できる！】Celestial Ring",
    "VERMILION ACCESSORIES v1",
    "≒ Gravity Drape ≒",
    "ラメピアスセット Y2K Jewels",
    "ボサスト",
    "コットンキャンディツインテール🍬CottonCandyTwintail【まめふれんず・タルトタタン・コロネ・ビスキュイ・しらつめ】",
    "【無料】こどもランドセル２",
    "【MA対応】ゆらゆら にょ〜〜ん 猫",
    "〚♡Radiant-Iseoアクセサリー2025♡〛",
    "【VRC想定】パンクなピアスセット ver2.0",
    "やる気３％Hair",
    "【無料】アンティークアクセサリー【3Dモデル】",
    "ねこみみリボン🎀 ⋱40,000 Followers Anniversary Goods⋰",
    "Eternal Horn【MA対応】ドラゴン/悪魔の角",
    "【描ける!身に着ける!】Colorful Pallet Pin",
    "【29アバター対応】眼帯｜Eyepatch",
    "【無料】†Noir Cross† ヘアアクセサリー（地雷系喫茶らんどまいん2周年記念）",
    "ミュート食パン【VRChat】",
    "DEADHALO-",
    "髪の花ごよみ【3Dアクセサリー】",
    "✨6アバター対応✨ ☁️Space Cat☁️",
    "CrossGlasses",
    "Eyewear 05【VRChat想定】",
    "⁺‪.°ʚ  MizuMelo  ɞ°.⁺‬  水がゆれる！ ヘアアクセサリーセット (+バッグ)",
    "【無料】Lumiere -ピアス-",
    "【無料】「必死にしがみつく猫」【VRChat向け】",
    "【無料】FrostCrystalHalo【MA,アニメーション,パーティクル付きヘイロー&ヘアピン】",
    "🌹Gothic Forfex🌹【MA対応】",
    "33 Avatars | ☁ AiryHair",
    "【FREE/無料】【VRChat】🦋JewelButterfly🦋【MA対応】",
    "【VRChat想定】連れて歩ける！管入りモナカ",
    "リキッドヘイロー -LiquidHalo-【#EvicPlus】",
    "キプフェル専用 きらきら星ヘアアクセ💫",
    "春まち花かんむり【VRChat】",
    "【無料ෆフォロワー2000人記念】Ribboned Harmony",
    "【動く】Ethereal Glow - 天使アクセサリーセット【VRChat向け】",
    "メガ着替えギミック【腕輪/指輪/イヤリング】",
    "【thx1000followers】Celeste Garter - ガーターリングアクセサリー【VRChat向け】",
    "！！SALE~8.31 ！！ 🌕【FREE/商用CC0】手描き⁺500 Liltoon MatCap-Vol.1",
    "[FREE] メイドのサメちゃん！【ショップフォロワー200人記念！！】",
    "𖦹ʚ Acid Catɞ𖦹Tail+Ears+Collar",
    "【十字架追加】†Void Bind† ボディピアス",
    "【なみだめがね】눈물 안경 Radiant-iseo",
    "【Free】くろねこせっと【全アバター】",
    "【MA対応】Vital Rush アクセサリー【持てる!揺れる!】",
    "【VRChat】SWW-01",
    "[無料] iphone 14 pro",
    "【無料,무료】 Choker for 5000  #3BON",
    "【割れる!!】Shabon Angel Set",
    "[Grus/Lapwing] Low Ponytail",
    "【無料/Free】ami尻尾・触覚角",
    "✩FREE/無料✩ 「複数アバター対応」 Y2K Hair Clips",
    "【MA対応】掴める！おやすみアイマスク【ナイトモードギミック設定済み】",
    "Black Rimmed Glasses",
    "『VEDA ネモフィラ シルバーリング』VRChat向けアクセサリー",
    "首掛け想定ヘッドホン（3色差分・スタンド付き）",
    "🍩🎀 MoguMogu Delivery 🎀🍩",
    "🎀Kawaii Monster🎀",
    "マスク PB Mask (45アバター対応)",
    "MOFU EARS & TAIL🍒【3Dモデル For VRChat】ver1.0.4",
    "【動く】Sylvan Echo - 鹿モチーフアイテムセット【VRChat向け】",
    "【 無料 / free 】みるくヘイロー🍼🍓",
    "【無料3Dモデル】シンプルなバケットハット",
    "● KITTEN PACK ● 幼猫育成キット ●",
    "＋ニュアンスカール",
    "ゴシックフェイスヴェール（調整用ボーン・透過度差分テクスチャ入り）",
    "【100アバター以上対応】HiganbanaNail【VRネイルチップ】【MDollnail対応】 #あんらぼぶい",
    "ALBATROSS v1.1",
    "【無料/Free】FUSHI & 犬DOGE & いろP",
    "🤍ʚAngel Hairɞ🤍11アバター対応",
    "！！SALE~8.31 ！！ 💗【FREE/無料】Shinano100Type❥動くまばたきFace&PoseAnimations ⌖ ݁˚",
    "【VRChat】Lilith wing",
    "【Free】Bérine / earrings🍪 ＆ ribbon ring🎀",
    "無料！フォロワー1000人記念『リボン２！』VRChat",
    "！！SALE~8.31 ！！ 💗【FREE/商用OK/実物】悪＆光堕ち∔3TouchMysticTattoo↝《MA対応》",
    "Pitti Muffler -ピッティマフラー-",
    "ドレープリボン for Ayashige Highpony【3Dアクセサリー】",
    "！！SALE~8.31 ！！ 💗【FREE/無料】Milltina100Type❥動くまばたきFace&PoseAnimations ⌖ ݁˚",
    "Abyssal Vulpes -多眼狐面-",
    "！！SALE~8.31 ！！ 💗【FREE/無料】Rurune100Type❥動くまばたきFace&PoseAnimations ⌖ ݁˚",
    "【雨を降らせてビームも打てる!!】雨音の傘",
    "[無料/Free] Devil Horn&Tail (VRC/PB)",
    "Lapwing - Face Tracking Add-on",
    "【VRC想定】チェーンブレードプラス / Chain Blade Plus",
    "[PB対応] VRC用 Pretzel Hair",
    "⯌「ドロップピアｽ（DropPias）」３２アバター対応",
    "Ferrous Dissolve",
    "[MA対応]VRC内で好きな音楽を聴ける音楽プレイヤーギミック「RK Player」",
    "【6アバター対応】レッグチョーカー｜Leg Choker",
    "【アクセサリー】Straw hat ＆ Straw headband（無料）",
    "【蝶が飛ぶ!】Prism Glint 【20アバター対応】",
    "34 Avatars | ❤️Sweety Hair❤️",
    "≒ Versatile Hood ≒",
    "天国の花カチューシャ＋ピアス",
    "VRChat向け フェイスアクセサリー『月桜の雫』- Tsukisa Eye jewelry -",
    "【動く】Auriel Whim - 天使アイテムセット【VRChat向け】",
    "【40↑アバター対応】Lucent_Leg　-ルーセントレッグ-",
    "Cosmic ray ネックレス 3Dモデル",
    "elf ears-光を感じるエルフ耳-",
    "本型かばん",
    "金木犀アクセサリー",
    "【無料, FREE】 Cinnamoroll slipper ໒꒱ シナモロール スリッパ",
    "【Nihilist Blues】オーディオリンク対応ヘッドホン",
    "RealKissSystem リアルキスシステム【VRChat】",
    "さたにあ式タバコギミック【Modular Avatar】【アバター対応250体以上！】　#さたにあ式タバコ",
    "簡単導入♥心音キット！ v2_08 260118更新",
    "【Modular Avatar対応】自撮りギミック付きスマホ『TemPhone』🎀",
    "「ぱちゅぱちゅ音がなるギミックEX」SimpleSoundEffectPlusEX（SSEP）",
    "【vrchat】[free]MisoShadow",
    "VRC用 『メカ弾エフェクト』",
    "【VRChat】StrongerZero 拡張ギミック【飲酒マスター】",
    "3Dモデル「imagePad」+ VRChat Udon用ギミック",
    "【7アバター対応】ぬちょ唾液（音声ギミック付）",
    "【言葉をおぼえる】なんかしゃべるペット？「ムチォ」【MA対応】",
    "マタタビシガレット【キプフェル専用】",
    "VRChat向けリアルスマホギミック - BloomPhone 3【Modular Avatar対応】",
    "[VRC] Coffee Set - MiniGreen",
    "アバター用カタナキット",
    "【赤夜式】注射ギミック【VRCアバターギミック】",
    "【無料】[SDK3] VRCで使えるスマホ、vPhone",
    "白い吐息パーティクル",
    "【ねんどろいど発売決定記念】いいかんじの木の枝 / 無料3Dモデル",
    "【VRChat想定・MA対応】狛犬式・火炎放射ギミック",
    "(全アバターMA対応)VRC想定アバターギミック　タバコ、ライターセット　点火可能",
    "【無料】フォロワー3000人記念　触れたら割れる！風船ガム",
    "ぬいぐるみ抱っこギミック『くまちゃま』🧸🎀",
    "アニメとかでよく見る目が光るやつ!!!",
    "【MA対応】Bloom Phone 2 - VRChat向け多機能スマートフォン",
    "【MA対応】多機能フィンガーライト (VRChat想定）",
    "【アバターギミック】影領域エフェクト ShadowField【影シェーダー】",
    "【Modular Avatar対応】拳銃９ 射撃・リロード・スライド・残弾管理等アバターギミック付き【Pistol9】",
    "【VRChatアバターギミック】BindSystem",
    "Quest対応！無言勢のための持てる多機能アバターペン-YagiPen",
    "げんなま!!!【ギミック付】",
    "アバター用釣りギミック 終末世界釣行",
    "うきうき換毛期 / 3Dアバター用ギミック",
    "【無料】強制VR感覚スイッチ - V Switch -",
    "Elemental Bow | 元素の弓",
    "Nebula Staff | 星雲の杖",
    "【VRChat】Among Us Follower",
    "【VRChat】VRC Tea Time 紅茶セット（Worldギミック）",
    "【アバターギミック】ISOLATION-CUBE【Modular Avatar対応】",
    "【アバターギミック】捕獲されギミック",
    "Luminary Shooter - 光る生き物と銃ギミック",
    "首を傾げると？が出るやつ",
    "【VRChat想定】飲めるお酒",
    "【ModularAvatar対応】VRChat想定 Avatars3.0向けギミック 「DAGsHG No.02 M9A1」【銃／ハンドガン】",
    "サメのヘアアクセサリー",
    "洋酒おつまみ9点セット　食べられるUDONギミックのおまけつき",
    "【VRChat用】Integral カメラギミック",
    "【ギミック付3D武器モデル】EX-RIPSE【Gunrod】",
    "Stronger Zero チューハイ缶 3Dモデル",
    "【VRChat】VRC Siphon Coffee サイフォンコーヒーセット（Worldギミック）",
    "【飛行ギミック入り】魔法の箒 Magic Broom",
    "【MA対応・VRChat想定】プリズムチャージャー",
    "【MA対応・VRChat想定】フォーカード",
    "【ギミック付3D武器モデル】シールドファンネル - ICE Fortress - 【MA設定済】",
    "【MA対応】陽津神-ヒツカミ-【VRC用武器】",
    "【オリジナル3Dモデル】KUGINASABLADE-クギナサブレード-【カタナブレード】",
    "【3Dmodel】水斬 花筏【ModularAvatarギミック付】WaterBlade HANA-IKADA【Effect included】",
    "【便利ギミック付き】ふわふわUFO（MA対応）",
    "【MA対応・VRChat想定】ティアーノート",
    "【ギミック付3D武器モデル】千雨",
    "【ギミック付3D武器モデル】BellowMaker",
    "なでなでパーティクルギミック【VRChat】",
    "【MA対応・VRChat想定】ワールエッジ",
    "【無料】ポカポカ乱闘ギミック",
    "【10アバター対応】変形義手 Evo Arm　(中身差し替え可能)",
    "（耳かき無料!）【VR-ASMRツールセット 9種類】-VRChat用小物モデル",
    "【アバターギミック】RAY-LINE【Modular Avatar対応】",
    "【MA対応!!】お前が彗星になるんだよ！！！ver.2",
    "【無料】【ギミック搭載】B3 Wingman【TITANFALL2】",
    "【VRChat】Heart Aimer. 【UIで飛ばせる!❤パーティクルシステム】",
    "VRサウンドパッド",
    "【MA対応】VRChatで音楽が再生できる！ポータブルレコードプレーヤー U-IV Oberon",
    "【自動設定ツール付き!】絵に入れる！絵画ギミック",
    "パッチワークモンスター",
    "【無料】鎌と槌ギミック【VRCアバターギミック】",
    "【無料】シンプル家具セット72点（UnityPackage）",
    "きねこ式Vippoタバコシステム　KinekoVippoCigaretteSystem【Modular Avatar対応】",
    "【VRC想定】ビットシステム / Bit System",
    "【ギミック付き】肉球ポインター！（無料）",
    "”Kawaii SnapCam” シェアできるインスタントカメラ📸V1.21【全アバター自動セットアップ】【ワールドギミック利用可】",
    "【ギミック付3D武器モデル】荒噛【ARAGAMI】",
    "【無料/free】Donuts！【3D小物】",
    "【無料】【VRC想定】サイレントトーク / Silent Talk",
    "【アバターMAギミック】朧花の煙管/【MAGimmick】Sakura Smoking pipe",
    "【VRChat向け】【複数アバター対応/特殊作戦向け装備/B4NGSHEE \"バンシー\"】",
    "【ギミック付3D武器モデル】白鯨",
    "食べるギミックつき！チャイティー＆カフェセット（34点）アバター＆ワールド用",
    "Let's Go ショッピングカート 【乗り物系アバターギミック・MA対応】",
    "mechanic shark（ギミック付）",
    "アバター用シューティングキット",
    "Dangerous Box【汎用アバターギミック】",
    "なんでも!お散歩ギミック",
    "VRSNS向け住宅用洗剤『マヂクリーン』",
    "【VRC】残像移動ギミック PhantomMove【アバターギミック】",
    "Gothic Noir Accents",
    "無料【VRC想定】ホラーワールドヘルパー / Horror World Helper",
    "【無料 / VRC想定】- Optimus -",
    "【VRC想定武器】【無料】GRh-Ra HARVESTER ANTARES-74000",
    "パーティクル付きサンタ袋＆ソリセット",
    "【ギミック付き3Dモデル】APHG-23L&APKN-12【ハンドガン＆ナイフセット】",
    "❖ hide_KemoHands. ❖",
    "空間展開ギミック【MA対応】【VRChat想定】",
    "【無料】トンプソンサブマシンガン/M1921",
    "【VRChatアバターギミック】HangSystem",
    "抱っこsitギミック【VRChat想定】",
    "【無料】哺乳瓶/baby bottle【BOOTHフォロワー３００人記念】",
    "【無料】Crystal Lantern",
    "【無料/Free】🤍ほにゅうびん_baby bottle🤍【全アバター対応】【MA設定済み】",
    "【無料】スノードームになれるギミック【VRCアバターギミック】",
    "【VRChat向け】ギミック付きスマホ",
    "【MA対応】ポツポツ落ちる水滴ギミック(VRChat想定）",
    "演奏できる！サカバントーン【VRCアバターギミック】",
    "キッチンを作る予定が、気づいたら庭まで作っていたセット（多分530点）",
    "蝶パーティクル / Butterfly Particle",
    "【MA設定済】ゆらゆらオバケギミック",
    "【3Dmodel】仕込み刀 隠妖丸【ModularAvatarギミック付】/Preparation sword【MAGimmick included】",
    "【無料】フォロワー6000人記念　動く！うちゅうねこ",
    "AR-15 ESTOC | 1.32",
    "fbxモデル 銃鞘刀「NLK-820G」",
    "どこでも白米セット🍚【ModularAvatar対応】",
    "【オリジナル3Dモデル】Stingray-スティングレイ-【投げナイフ】※サポート非対応",
    "ミニ戦車（走行＆発砲ギミック付）",
    "【オリジナル3Dモデル】SP-9_VE&Thuban【ハンドガン＆ナイフ】※サポート非対応",
    "ルウちゃんカフェラテ / 無料3Dモデル",
    "世界初、VRで本格サイフォンコーヒー。どこでも開ける喫茶店 - ぶいサイフォン【VRchat】【MA対応Avaterコーヒーギミック】",
    "Ibera-Scythe【オリジナル3Dモデル】",
    "【無料】☾⋆⁺くまさん ⁺⋆☾ Teddy bear【セット衣装リリース記念】",
    "【魔法ギミック】ルミナスワンド【汎用】",
    "のびふぇるシステム(まめフレンズ対応)",
    "無料🌸【２人乗れるよ！】ふわふわかまぼこ号",
    "即刻有罪！どこでも裁判所セット⚖️【ModularAvatar対応】",
    "ワールド＆アバター用食べるギミック付き！アイス11種セット🍦",
    "【VRChat】ワールドメガホン / WorldMegaphone【UdonProps】",
    "スイーツビュッフェ10点セット　PC/Quest両対応　お皿に盛って食べられるUDONギミックのおまけつき Sweets Set",
    "加熱式たばこギミック サイズ - XYZE v1.1.4",
    "【VRChat想定・MA対応】狛犬式・氷結吐息ギミック",
    "【MA対応・VRChat想定】セレスティアルスペル",
    "【VRChat】 インタラクティブおしゃぶり Interactive Pacifier",
    "抗議デモスターターキット📢",
    "【3Dモデル】Punisher Custom Handgun v1.0.0",
    "【オリジナル3Dモデル】Weisklein91-W91-【コンパクトHG】※サポート非対応",
    "【VRChat想定・MA対応】狛犬式・熱線放射ギミック",
    "【VRChat向け】フラッシュライトギミック",
    "【3Dmodel】冰刃 雪那【ModularAvatarギミック付】/Ice Blade SETSUNA【Effect included】",
    "【MA対応】LUX-ORTUS【VRC用武器】",
    "ブイアールポケットゲーム【赤のまめひなた/緑のキプフェル】　携帯ゲーム機型３Dアイテム",
    "Lolita Umbrella",
    "【無料】ポスターパネル【VRC想定】",
    "口移しで融かしあうチョコ【VRChat】",
    "Snow orbit rapier | スノーオービットレイピア",
    "クラゲパーティクル / Jellyfish Particle",
    "つやつやロリポップ🍭",
    "闇取引スターターキット💼【ModularAvatar対応】",
    "【無料/Free】超かぐや姫改変セット【非公式モデル】",
    "【Avatar/World対応】食べられるチョコレートギミック | Chocolate【VRChat想定】",
    "M9A3 （Ready to Shoot!）【ギミック付き3Dモデル】",
    "【MA対応】服薬ギミック",
    "食べれる！スティックお菓子セット🍬【ModularAvatar対応】",
    "24曲入る！【赤夜式】ラジカセギミック【VRCアバターギミック】",
    "[無料]お手軽スライドショーフォトフレーム",
    "いつでもどこでも自分だけの喫茶店 - ベルギーサイフォン【VRchat】【MA対応Avaterコーヒーギミック】",
    "【MA対応】選んで切り替え！衣装チェンジキューブ(VRChat想定）",
    "【24/03/30更新】宇宙を感じる数式パーティクル",
    "Kip-Boy【VRChat想定】ギミック付きアクセサリー",
    "ゲーム機のカメラギミック",
    "「BLVK 2nd Anniv Novelty」オリジナル3Dモデル",
    "焼肉キット　PC/Quest両対応　焼いて食べれるUDONギミックのおまけつき Eatable BBQ Set  야키니쿠",
    "【無料/free】もぐもぐくらげ【3D小物】",
    "無料3Dモデル 『スレッジハンマー / Sledgehammer』",
    "ハート飛ばしパーティクル＆パーティクルハートガン",
    "【ModularAvatar対応】VRChat想定 Avatars3.0向けギミック 「DAGsAR No.01 US416」【銃／長銃／ライフル／アサルトライフル】",
    "【非推奨】パラメーター同期式ワールド固定システム【VRChat】",
    "【無料】【VRChat想定】Gem Clock",
    "無料「VRCHAT」ワールド固定アイテム自動設定ツール",
    "【無料版】ヨーヨー風船",
    "【ギミック付きパーティクルワンド】LuminousGardenWand【【MA対応】",
    "[for VRChat]弓/双剣(LongBow/Twinblade)「ハバキリ(Habakiri)」[Weapon Model]",
    "とろりとしたたる液体 [アニメーション・PB設定済み]",
    "【VRChat】『ALGEBRA Camera Console』《カメラギミック付き》",
    "GPU Fish Particle / GPU魚パーティクル",
  ]),
  __multi_tool__: Object.freeze([
    "【無料】lilToon",
    "もちふぃった～",
    "リアル影システム (for Avatar) PCSS For VRC",
    "VirtualLens2",
    "つぶせる！押せる！ましゅまろPB(Marshmallow PB)",
    "[無料] AAO: Avatar Optimizer",
    "【VRChatアバターギミック】AvatarPoseSystem",
    "誰でも触れる！もっちりシェーダー(Motchiri Shader)",
    "【MA前提 ライティング調節ツール】 Light Limit Changer For MA v2",
    "【赤夜式】撫で音ギミック【VRCアバターギミック】",
    "GoGo Loco｜System｜1.8.6",
    "『Avatar Blink Fix』表情改変後の目のBlendShapeを修正するツール",
    "【無料】VRCQuestTools",
    "QvPen",
    "【全アバター対応ギミック】フェイドアウトシステム Ver.2.0 FadeOut System for LilToon（Modular Avatar対応）",
    "【VRChat】LAC: Avatar Compressor (Beta) ｜ アバターを簡単・劇的に軽量化",
    "AvaPo！（Unityでポーズ作成&撮影ツール）",
    "AvatarBasicTool｜10種以上の便利機能や姿勢変更など",
    "【無料】FloorAdjuster（VRCで足が埋まる/足が浮くのを直すツール）",
    "【無料】AvatarMenuCreator for Modular Avatar",
    "【Unityメッシュ編集ツール】EreMorph",
    "なめらか心音ギミック 3.0【OSC心拍計対応】",
    "【VRC睡眠システム】3点トラッキングでも快適にVRC睡眠！【VRC sleeping system】",
    "【アバター衣装変換ツール】きせった (Kisetter) V3.1.3",
    "【超リアルな撫でを追求】なでなでギミック：リアルなでシェーダーVer.3.0",
    "Shadowdepth Shader(史上最高のなでなでを追い求めるVRC民に贈る深度影再現シェーダー)",
    "【無料】Siromori Eye Pointer",
    "【VRChat】非対応髪も一瞬でピタッ！髪の毛総合支援ツール「Kami-Pita（髪ピタ）」",
    "【195アバター対応】非対応アイテクスチャを使えるようにするツール V3.6",
    "Breast Physics Plus Plus 物理演算胸揺れギミック",
    "チュパサウンド JustKissSFX",
    "【改変幅拡大！】VRCブレンドシェイプ限界突破・合成ツール",
    "アバター軽量化プレハブ",
    "【無料】Meshia Mesh Simplification",
    "髪キメラの色統一と色変えとメッシュ変形までするやつ\"キメラヘアマスター\"v1.5.10",
    "See Through Hair",
    "【無料】みんなでつかめるだこちてギミック - Hold Gimmick",
    "食い込みシェイプメーカー Kuikomi Shape Maker",
    "【無料】複数アバターちびっ子化prefab【キプフェル必須】",
    "【フカさんの！】撫で音ギミック【VRChat】【MA式】",
    "全身Grabシステム (アバターギミック) GrabFullbody",
    "Blackout Shader(頭の中を絶対に見られたくないVRC民のためのシェーダー)",
    "SyncDances 4.5",
    "KonoAsset - VRChat向けアセット管理ツール",
    "【簡単‼️】VRC首すげ替えツール【30アバター対応】【VRC Head Replacing Tool】",
    "【無料】あの子のコスPrefab(K)",
    "【簡単導入】ふんわり影シェーダー【lilToon拡張シェーダー & 導入ツール】",
    "【V睡】RBS SuiminSystem 2 - メニュー操作なしで寝返り / OVRで高さ調整【ModularAvatar対応】",
    "【簡単！】MMD表情設定ツール",
    "無料[MA対応]Simple Setup SPS Hole",
    "【無料あり】MMDワールドの表情動かすやつ【VRC想定】",
    "MeshSyncPro",
    "【VRC向け】催眠エフェクトギミック＆催眠瞳シェーダーV1.4",
    "【無料】BlendShare - シェイプキー配布, blendshapes extraction & distribution",
    "lilSSRT",
    "つながる、歩く、感じ合う。【シン・アバターリードシステム】",
    "【無料】lilAvatarUtils",
    "【アバター体格改変ツール】ちちをもれ！【巨乳お姉さん体型化改変・デフォルメ頭身化】",
    "lilSSAO【lilToon拡張】",
    "SittingAdjuster | 判定に座った時の高さとポーズを変更",
    "【Unity完結】ずらしギミックジェネレータ【VRChat】",
    "「ギミックつく～る」 - アバターギミックを作るギミック -",
    "☆無料配布☆「NoriBlocker」ベタ塗り表情無効化ギミック【Mobile対応】",
    "非破壊でメニューの並び替えや、削除などを行える！「Expression Editor」【VRChat】",
    "【All Avatar対応】SPS 【MA】",
    "【無料】lilycalInventory",
    "【3点でも足を動かせる】あしウゴカシ【脚なで・踏み・撮影ポーズ】",
    "Lume Optic 目シェーダーシステム",
    "【無料】魚眼レンズ風ギミック v1.25",
    "【無料！】メッシュに色を付けれるツール！ #kokoa_factory",
    "VirtualLens2対応 カスタムカメラギミック VR169 (3D Model)",
    "テクスチャを直感的に貼り付けるツール V2.2",
    "SOM2.0｜自分の姿を表示できるギミック",
    "Blackbody Shader(アバターの裏側という概念を抹消したいVRC民に捧げるシェーダー)",
    "【MA設定済】【VRCPOS】VRC Photo Overlay System",
    "【落ち影システム】ワールドにあなたの影を【Ochikage】",
    "【VRC脱衣システム】ふわぬぎ【VRC Undressing Gimmick】Fuwanugi",
    "✨GestureSound ジェスチャーサウンド (口&手)【VRCアバターギミック】",
    "【カメラポーズで撮影!!】Gesture Cam",
    "【VRChat】Flex FishEye Lens  & [+DoF]",
    "【1.8.6対応】GoGoLoco for MA+日本語化 - ワンクリックで自動インストール＆修正！",
    "なでなで産卵システム【全アバター対応（たぶん）】",
    "BlendShapesコピペツール",
    "Merge Tool",
    "【デスクトップで腕を動かす‼️】無料!!【VRC Hands Moving System】",
    "PoLKA: Portable Light Kit for Avatars",
    "[VRChat]手を動かすと音が鳴るなでなで音ギミック[MA対応]",
    "HeightChanger｜高さと視点を調整(既存の移動モーションや姿勢を維持します)",
    "「ふぇいとらでき～る」 - VRChat フェイストラッキング 自動導入＆顔トラ改変ツール（MA対応） -",
    "💦 Real Sweat System 【汎用アバター対応】",
    "握手ギミック",
    "【無料】非破壊の色改変ツール / Color Changer For Unity",
    "【VRChat】ペイントソフト不要で一瞬作成！マスクテクスチャ作成ツール「HayaNuri!（はやぬり！）」",
    "【VRCスケールチェンジシステム】VRChat上で大きさを自由自在に変えるギミック【VRC Avatar scaling System】",
    "【簡単導入】幻影シェーダー【lilToon拡張シェーダー & 非破壊導入ツール】",
    "LIGHT3R!!【全アバター対応】*",
    "【VRCグライダー&ダッシュシステム】空中を滑空＆素早い移動‼️【VRC Glide Jumping System】",
    "TextureColorKit｜色変更・AO/SDF生成・アバター最適化ツール",
    "【旧型】アバター引っ張りギミック【アバターリードシステム】",
    "PoseClipper｜アバターの身体を部位ごとに固定！",
    "【VRC用】圧迫されるおっぱい【ましゅまろPBアドオン】",
    "MMD Eye Fix",
    "【PC/Quest】PPPen -持てる指ペン / アバターペン-",
    "【桔梗推奨ギミック】カードトリックギミック「ワイルドトリックスター」Card Toss System Wild Trickstar（Modular Avatar対応）",
    "綿飴屋シェーダー三種セット(Wataameya Shader Set)",
    "超簡単MA着替えシステム（現在50アバター対応）",
    "【無料】お前もロリにならない化？Prefab",
    "SynchroMotionSystem｜ボタンを押した人と一緒に踊ったりできる",
    "Normalmap Generator【ノーマルマップ生成ツール】 #dennokoworks",
    "VRCだっこシステム【VRC Lift Up System】",
    "【もっちりシェーダー簡単導入！】セットアップツール【MotchiriShaderSetup】",
    "どこどこテクスチャ",
    "【VRChat】Follower System 好きなアバターを連れ歩けるシステム",
    "【無料！】Enable/EditorOnly 簡単切り替えツール #kokoa_factory",
    "【完全無料】「Pen-Ta」Trail式アバターペン【Mobile対応】",
    "【lilToon専用】One Fade Out (Modular Avatar使用)",
    "【無料‼️】VRCのび〜るほっぺたシステム【VRC Cheeks Pinching System】",
    "[VRChat]　DHT　デスクトップヘッドトラッキング",
    "CapFitter/HoodieFitter",
    "【V睡向け】呼吸音ギミック",
    "【VRChat】胸揺れPlus (アバターギミック) Breast Physics Plus",
    "【無料】lilEditorToolbox",
    "【VRChatアバター体型コピー＆調整ツール】Silhouette+(シルエットプラス) Unity Editor拡張",
    "【VRChat想定 首絞めギミック】DEEP CHOKE",
    "シーン上でメッシュを選んで紐づいてるボーンを簡単選択！「BoneScanner」【VRChat】",
    "【liltoon】機能盛り沢山！リアルなでさわシェーダー（Uzumore-Shader/うずもれシェーダー同梱機能強化、一括設定ツール込み）（AOマップ簡易作成ギミック付き）（その他タトゥーやリムライトなどなど！！）（投げ銭の人は乳影SSAO追加）【JP/EN】",
    "【55アバター対応】V睡用に目を閉じてパーティクルを出すメニューを追加するギミック【MA対応簡単導入】",
    "Stylized Interactive Menu（Modular Avatar）",
    "【全アバター対応】簡単に体型・衣装のスケール変更「スケールエディター」",
    "【Free】Milltina Face Plus",
    "【VRC想定】グリッチオーバーレイ / Glitch Overlay",
    "【無料】Armature Scale Copier",
    "【SALE👻】幽霊プリセット-Ghost Preset-【lilToon Preset】",
    "Gradation Baker【グラデーション簡単作成Unity拡張機能】 #dennokoworks",
    "アバター頭乗せ人形化ツール / AvatarDollSystem【VRChat】",
    "【無料】対応衣装スケール調整ツール (Outfit Scale Adjuster)",
    "【MA対応】アバターを幼くするツール V4.10",
    "[Free]Liltoon Extra Alpha Shader",
    "【VRChat】メニュー整理ツール「NDMF ExMenu Organizer」",
    "ALCOM - A fast open-source alternative of VRChat Creator Companion (VCC) for macOS (Mac) Windows and Linux",
    "【無料】ハイタッチギミック【仲良しのやつ/グータッチ/ビンタ/ツッコミエフェクト】",
    "RQIConverter",
    "【無料】[VRC]サブアバターギミック (20260725更新)",
    "UMHL LightingEnhancer",
    "【ModularAvatar対応】口と足でPBに干渉できるようにするツール-DynamicsAdvanceSetter-",
    "💤逆光ライト💤『逆光コピー / ONOFF生成』ツール【MA対応 / liltoon専用】",
    "VirtualLens",
    "全天球カメラシステム【MA対応】#360VRC",
    "VRChat ワールド用の防音室ギミック / Attenuation Tool",
    "【無料】Unity色分けツール / ColorLabeler",
    "【VRChat】パンツ覗くと視界ジャックされるやつ",
    "【MA】Knee Fixer",
    "ぐるぐるだっしゅ！【アバターギミック】",
    "【VRChat】ねこやの腕固定システム",
    "一瞬でアバターに彩りを！簡単UVグラデーション自動生成ツール 【Gradelu】",
    "WeightSyncPro",
    "【MA】 Light Controller",
    "【VRC表情追加&固定システム！】VRC上で使える表情を追加&固定機能を簡単導入！【VRC Facial Expressions Setting System】",
    "(無料！導入簡単！)空中を一緒に移動できるギミック【VRC Together Flying System】",
    "Harune Avatar Enhance [lilToonカスタムシェーダー]",
    "【Unity用】Mew【エディタ拡張】",
    "【無料】VRCJapaneseInputter",
    "【一括管理！】WriteDefault切り替えツール(WriteDefaultChanger)",
    "「MA対応」小っちゃい子連れていける！肩車ギミック！",
    "腕組み、手つなぎギミック",
    "【無料】天候&太陽システム【VRChatワールドギミック】",
    "【無料】誰でも軽量化を簡単にEasyAvatarOptimizer",
    "【VRC】後ろを追従するギミック【VRC Back Follow System】",
    "【新登場】EDEN Mesh Studio (エデン メッシュ スタジオ) V2.0.0",
    "PVLController -VirtualLens2用お手軽自撮りギミック-",
    "ダンス用エフェクトギミック「JustStep!」",
    "QuickCamera【VRChat/アバターギミック】",
    "(VRChat想定アバターギミック)Parkour System V2 MA対応",
    "【Android/iOS対応】アバターギミック「Easy Floater - ゆるふろ -」【Modular Avatar対応】",
    "【無料】かろやかテクスチャ（軽量化ツール）",
    "【無料】おちびちゃんズ化ツール（Ochibi-chans Converter Tool）",
    "【無料版あり】パッと撮って、すぐ共有。【VideoCap】",
    "ワールド統合メニュー (World Integrated Menu) 【VRChatワールドギミック】",
    "【VRChat】ColliderDropDX コライダードロップ Avatar world-collision tool!【ModularAvatar/NDMF】",
    "【無料】NailFitter｜VRChat向け非対応ネイル自動フィッティングツール",
    "【無料/Free】Cyberpunk glasses♥",
    "【52アバター】宙の詩EyeTexture【10Color＋10】",
    "【48+αアバター対応】水中ソックス🫧-Water Socks🫧",
    "【リアル肌】Realistic skin Material - 調整済みマテリアル",
    "【40アバター】黄昏の微睡EyeTexture【20color】",
    "✨大型アップデート✨お姉さんミルティナ✧メイク・アイテクスチャ＋ブレンドシェイプ✧Makeup＋Eye texture＋Face Blendshape",
    "【35アバター】夜空の夢EyeTexture【38Color】",
    "✨輝夜/コマネ/リュミィ追加✨【無料】64アバター対応 眉毛の色を変える時に使えるマスク",
    "✧˖°⌖꙳Lueur Series ✧˖°⌖꙳ - Lueur Body -",
    "Add Your Fav🖤 +29アバター対応+",
    "リアル生感肌マテリアル【紗夜-Suzuya-_対応追加！】",
    "【31アバター対応】Melowpurity Eyetexture -メロピュリ- #MEMEROLAND",
    "【39avatar対応】MELOW Eye texture",
    "【34アバター対応】ツヤツヤ舌テクスチャ",
    "✨Misaki/彼方/しゅあん/リンネ追加✨【無料】51アバター対応 リムシェーダー適用時に使える目のマスク",
    "【無料配布】イラストAIで生成したmatcap素材149枚、さらにそのまま使えるマテリアル1549種類入り",
    "蝶と薔薇のタトゥー 15アバター対応[VRC想定/デカール]",
    "🔥SALE🔥∣🩶Void Gaze🩶 Eye Texture【45 Avatars】#PITShop3D",
    "【9アバター対応】Makeup & Eyes texture 10collar＋Ring Set 束縛メイク",
    "[16 Avatar] ⁘MOMO⁘ EyeTexture",
    "【liltoon】Poiyomiで良いとは言わせない究極の質感肌",
    "動く水マテリアル",
    "【Shinra】 Makeup texture No.2",
    "【22 Avatars】 Obje Eye Textures (8色 8Color)",
    "【ルルネ／rurune専用】Hair グラデーション&メッシュ・尻尾グラデーション",
    "【26アバター対応】cyber cat eye texture",
    "【複数アバター対応】なめらかマットマテリアル・SDFテクスチャセット【VRChat】",
    "ʚ 17アバター対応 ɞ 白鳥座 瞳テクスチャ",
    "✧˖°⌖꙳Lueur Series ✧˖°⌖꙳ - Lueur Makeup -",
    "5000人突破記念無料アイテクスチャ【AURORAJuicy-おーろらじゅーしー-】",
    "Cyberpunk-style Neon Translucence Material⚡サイバーパンクスタイル 霓虹半透明材質",
    "【Real Skin v.2.00】Liltoon Material",
    "おいしい肌 - liltoon肌質感プリセット",
    "【24アバター対応】🩸Twilight eye texture🩸",
    "【無料】【16アバター対応】 Lovable Eye Texture ❊Pluie❊",
    "【うらら追加】波が動く*秘密の水面(みなも)アイテクスチャ",
    "2種のミルティナ肉感もりもりボディテクスチャ+おまけ褐色肌テクスチャ ✧Milltina Body Texture✧",
    "Cyberpunk-style Transparent Material ⚡サイバーパンクスタイルの透明素材",
    "【30avatar対応】Draco eye texture【VRC想定】",
    "【無料】著作権放棄 Matcap",
    "♡汎用向け lilToon プリセット『アニメ風スキン』マテリアル設定♡-♡Universal lilToon Preset: Anime-Style Skin Material Settings♡",
    "【WHrim v.2.00】Liltoon Material",
    "【39アバター対応】彩度低め大人アイテクスチャ",
    ">1.01< 【SHINANO :: しなの】 Shinano make up & body texture :: しなの メイク テクスチャ",
    "イケ女しなのメイク・アイテクスチャ+ブレンドシェイプ✧Makeup＋Eye texture＋Face Blendshape",
    "爆イケ白肌マテリアル(汎用)＋おまけミルティナメイク🤍Anoyo skin Material+Milltina Makeup",
    "【15アバター対応】 Opalescent Tears Eye",
    "〖10avatar対応〗 Heroine Eye ⟡ アイテクスチャ",
    "13アバター対応【Free】無料 球体関節人形テクスチャ（他アバター用関節透過PNG付）#MURASAKIYA",
    "ʚ 15アバター対応 ɞ Juicy Eye Texture 🍍ˎˊ˗",
    "【48+αアバター対応】水中グローブ🫧-Water Gloves🫧",
    "ミルティナ / 褐色用メイクテクスチャ＆褐色肌設定",
    "しなの / 𝑨𝒔𝒂𝒚𝒂𝒌𝒆 𝑴𝒂𝒌𝒆𝒖𝒑",
    "【ミルフィ - Milfy / クマリ - Kumaly】しろくま Makeup & Eye Texture",
    "【Free/無料】肌用マットキャップ＋おまけ",
    "【📢NEW 輝夜 対応 ● 25アバター対応】 Lovable Eye Texture ✞Blanche✞",
    "31Avatar＋30Color >> 🌙Noctilume EyeTexture",
    "【31アバター対応】 BlackBerry Eye Texture",
    "【無料8avatar対応】×AURORA× eyeTexture＿0.0",
    "【マヌカ(Manuka)専用】Eyes+Makeup+Body Tex-Starry Lake-[HD-PSD]",
    "【しなの専用】Hairグラデーション・メッシュ【セットアップ動画付き】",
    "【liltoon】汎用BodyMateria/matcap　むちむち肌❣",
    "シャボン玉風マテリアル",
    "【彼方 狛乃 水瀬 斑霞 対応】Makeup & Eyes texture 4collar めろメイク",
    "【Kipfel/キプフェル】 AREN_Cloth Texture",
    "【無料7avatar対応】光の当たり方でハイライトが現れる！らぶりーばれんたいんあい＿eyeTexture",
    "【１６アバター対応】♡LOVE YOU!! Eye Texture♡",
    "【うらら追加】おやすみなEYE＆Lush🌙動くアイテクスチャ",
    "[25𝐴𝑣𝑎𝑡𝑎𝑟]✝𝑆𝑖𝑙𝑒𝑛𝑡𝑉𝑒𝑖𝑙✝ #Aspartame_VRC",
    "【FREE!】angel ring matcap【汎用hairマットキャップ】",
    "【無料お試し版あり】こまいぬmatcapセット vol.1【武器・小物向け】",
    "【15アバター対応】 AUREOL ~ Eye texture ~",
    "【Free】Normal Map3《3000フォロー記念》",
    "♡Toxic cat♡Makeup+Eye tex+Bandage【7アバター対応】",
    "【Sio】 makeup texture for ver.2.0",
    "【19アバター対応】💙君を射止める💙 cool eye texture",
    "【VRChat】Sexy skin material for VRC - どのアバターにも使えるセクシーでリアルなスキンマテリアル (MATERIAL ONLY)",
    "ヘアマテリアル",
    "【10アバター対応】⟡.·Lovesick Eye Texture",
    "【22 Avatars】 Devil Eye Textures (8色 8Color)",
    "【22アバター対応】🫧Watery eye texture🫧",
    "【Free】Normal Map2《500フォロー記念》",
    "【28アバター対応】☁️🍭わたあめ🎀アイテクスチャ🍭☁️【カラバリ16色】",
    "誰でも白リム界隈マテリアルプリセット(liltoon)",
    "【うらら対応セール中！】お魚が泳ぐ🐟🫧あわあわ水光 Eye Texture【10Color】【20Avatar】",
    "Spank me 🖤 +20アバター対応+",
    "【 PIROUETTE 】メッシュ ヘア ～ 16色 ～ Minimal Wolf Hair",
    "ぬるリング肌マテリアル リアル系 【liltoon対応】",
    "【ミルティナ専用】Milltina makeup texture ＋舌テクスチャ ✧Tear✧",
    "【3Avatars】TOXIC POP Eye ＋ Makeup texture【Sio/ショコラ/クマリ対応】",
    "【ルルネ - Rurune】ほわいとしゃ～く Makeup & Eye Texture",
    "【狛乃(Komano)専用 】Makeup+Eyes+Tongue texture+Material[HD-PSD]",
    "【7アバター対応】Cyberpunk-Body Tex+Material♥",
    "【ルルネ-Rurune】⟡.·Rurune makeup&eye texture",
    "Harune Hair Nomalmap＆Matcap",
    "‎ʚɞ SHINANO, しなの‎ ʚɞ Shinano pure make up & body texture ‎ʚɞ しなの メイク テクスチャ",
    "【VRCに簡単導入！】モーションタトゥー（心電図）【アニメーションデカール】",
    "🖤FREE🖤 【Shinra】abs body texture",
    "【27アバター対応】動くアイテクスチャ 7種/ Animation Eye Texture / WAVELOOP",
    "【19Avatar】MM Eyetexture+Face animation",
    "✨大型アップデート✨お姉さんしなの✧メイクテクスチャ＋ブレンドシェイプ✧Shinano Makeup texture＋Face Blendshape",
    "【18アバター対応】Aurora Eye Texture ♡",
    "【森羅-shinra】 𝐍𝐀𝐓𝐔𝐑𝐀𝐋♦ EYES&MAKE UP PACK",
    "【Sio/しお専用 】DOLL Makeup & Eyes texture",
    "【13アバター対応】 Malang ~ Eye texture ~",
    "【Lumina】 Makeup texture No.1",
    "【キプフェル専用】kipfel white make up【無料 / Free】",
    "【マヌカ(Manuka)専用】Body Texture Real skin[HD-PSD]♥",
    "【LUMINA/ルミナ対応】Makeup&eyes 7collar",
    "✧˖°⌖꙳Lueur Series ✧˖°⌖꙳ - Lueur Eye -",
    "ラメ入りピュアメイクテクスチャ / しなの",
    "めっちゃ！あにめまてりある(#あにまて)",
    "【 5 Girl Avatars 】 Snow Cotton makeup texture",
    "⯎ Milltina :: ミルティナ ⯎ Milltina pure make up & body texture + Face Blendshapes ⯎ ミルティナ メイク テクスチャ",
    "【rurune】Makeup Texture & Body Texture",
    "【Free】\"cyber\"Material《2000フォロー記念》",
    "【VRC想定】リアルっぽい口内【複数対応】",
    "FREE!【キプフェル専用】ヘアグラデーション&メッシュインナーセット",
    "【12アバター対応】Cyberpunk eyes texture♥",
    "💕𝑴𝑶𝑵𝑼 𝑬𝒀𝑬 𝑵𝒐.𝑰𝑽 𝑭𝒓𝒆𝒆𝒅𝒐𝒎 𝑯𝒐𝒏𝒆𝒚 𝑬𝒀𝑬 💕",
    "可愛いポーズツール　～３点でもVRChatで可愛い！～",
    "【無料】ごろ寝システム【Modualr Avatar対応】",
    "EmoteCollector | 大量のエモート枠&睡眠エモート",
    "【VRChat】Dynamic Gesture ダイナミックジェスチャー",
    "粛聖!! ロリ神レクイエム☆ Motion",
    "「Doodle Dance」 Motion",
    "(無料版有り) 【ポーズ詰め合わせ】Unity Humanoid AnimationClip - PoseCollection",
    "【VRChat】拡張ハンドジェスチャーV3【通常版無料】",
    "可愛い座りツール",
    "(無料)【 EmoteBox 】(ライト向け)_VRChat ExpressionsMenu",
    "VRChat AFK 3種セット",
    "「INTERNET YAMERO」 Motion",
    "【無料】お座りロコモーション（MA対応）",
    "「もぐもぐ」 プロジェクト",
    "【無料版あり】ポーズ集 - 1 -【全118種】",
    "【無料有】モーションセット 《2,000フォロー記念！》",
    "にょろにょろロコモーション",
    "キプフェルの瞳孔を消すだけのやつ【MA対応】",
    "【無料/Free】キプフェル専用　表情パッケージ63種",
    "【MA対応】しっぽプロペラモーション（キプフェル・まめひなた・ネメシス）",
    "【無料】VRC向けホバー移動モーション",
    "ハイハイ移動モーション【Sit判定付き】",
    "【無料】 1000 followers Thank you ✨Oshare Pose✨",
    "簡単導入＆簡単設定！姿勢変更ギミック改【VRChat】",
    "なでキュン💛システム（13アバター対応）",
    "【無料版あり】キプフェルちゃん表情セット！46+10種",
    "モア AFK スマートフォン",
    "【無料版有】みかん製ポーズ集Ver.４",
    "【VRChat】パフパフギミック",
    "すやすや〜アニメーション〜",
    "【V感注意】動くなでなでハンドジェスチャー（MA対応）Moving hand gesture for headpat",
    "VRChat ヲタ芸",
    "ハンドジェスチャー(24種)✋追加＆切替ギミック『ハンドジェスチャーEX』",
    "【無料版あり】メンズポーズ集【全110種】",
    "【無料】【MA対応】ホバー移動モーション【VRC想定】",
    "膝立ち移動モーション【6種類】",
    "[Free] Random Pole Dance System for Avatar 随机钢管舞组合系统 v1.0",
    "(無料版) Emote詰め合わせ - VRChat Emote ＋ Unity HumanoidAnimationClip",
    "【無料】 2000 followers Thank you 🐾Cat Pose 🐾",
    "【無料有】モーションセット 《1,000フォロー記念！》",
    "Arona Dance Animation",
    "【無料】呼吸アニメーション心拍数自動同期化Mod【ModularAvatar対応】",
    "ミルティナちゃん専用 エッチ♥な表情アニメーション",
    "おばけ風ロコモーション GHOST LocomotionLayer",
    "【22体アバター対応】可愛いハートが作れるハンドジェスチャー【1set￥150円】",
    "【 無料 】- Free Pose set - 30個 +♡ 支援版 35個",
    "[無料]ふわふわ雲のAFKモーション",
    "【無料版】Avatar Fade System【複数モデル対応】",
    "【Free】Deviate Pose + SceneSet",
    "【無料】撮影向けスケベポーズ集",
    "【無料有】モーションセット 《3,000フォロー記念！》",
    "[無料版有り] 立ちポーズセット-Standing Pose Set- For Kikyo",
    "【ハンドサイン改変ギミック】もみもーしょん【簡単導入・MA対応】",
    "【無料】撮影向け足見せポーズ集",
    "ミルティナ イケ女化 blendshape",
    "【無料版有】みかん製ポーズ集第二弾Ver.3",
    "【キプフェル専用】ぷるぷる♪表情アニメーションセット",
    "ハンドモーション Handmotion",
    "tailshop POSE SET vol.3",
    "ꗯ̤̮  50種類  *｡ / pose set [SOLD 1K♡memorial SpecialThanks!]",
    "まめフレクレーンゲームAFKギミック【MA対応】",
    "添い寝ツール",
    "【全28種】写真撮影向けハンドジェスチャー【MA対応 Expression Menuからの呼び出しギミック付き】",
    "【お試し版あり】ハートポーズセット",
    "HappyHallowe'en👻おばけのアニメーション",
    "キプフェル無表情ギミック＋表情パーティクル",
    "【無料】まめひなた向けポーズアニメーション23種",
    "【VRChat】サイバーなスクリーン v2【AFKモーション】",
    "【簡単導入・複数アバター対応】撮影用ポーズ集39種【一部無料】",
    "【うるうるまばたき】「Animation Set」「New！ミルティナ対応」",
    "Meme Motions! 【INTERNET YAMERO】【強風オールバック】【Unwelcome School】",
    "【MA対応】ルルネのサメちゃんライド",
    "【💗FREE💗】POSE SET【無料ポーズ×17】",
    "[無料版有り]おすわりポーズ -Sit down Pose Set-For Kikyo",
    "Shinano(しなの)'s FacialTracking Setting",
    "【ポン置きOK】駄々こネコチヤン【アニメーションセット】",
    "【LUMINA対応追加！】【さたにあ式タバコギミック用】追加ジェスチャーギミック【MA対応】(2025/10/28更新)",
    "ガラス破壊【MA対応・アバターギミック】",
    "【無料版有】minuit poseset-02【FREE Sample】",
    "【MA対応】キプフェルしっぽの抱き枕　（ポーズシステム）",
    "009.【無料有】服やアバターのちょっとした紹介に使えそうなanimationファイル",
    "HopeskyD 足足プロジェクト",
    "Toothless Dance Animation [Free Emote]",
    "ワールドで良い感じに映えるポーズ集",
    "【無料ポーズ】25年10月ポーズ 15個",
    "【無料】着物・和服向けポーズアニメーション",
    "(無料)【あの技モーション 詰め合わせ】ｰ Unity用モーション+VRChat ExpressionMenu",
    "【無料版あり】”Look at me！”tailshop POSE SET vol.2",
    "[無料、ﾚｲﾔｰ配布]フルトラじゃなくても可愛く座りたい！！！「内股座り」",
    "FacialTracking for Manuka(マヌカ)",
    "♡LovePoint Cute Pose Set 28個♡",
    "008.【改】【無料有】色々動いてくれるのでアバターの動作チェック等に使えるanimationファイル",
    "お年玉ガトリング【MA対応】",
    "【無料 ～ 10,000人フォロー記念】モーションセット",
    "ホットドッグAFKモーション【まめひなた用】",
    "写真向け！決めポーズアニメーション35種",
    "【無料/Free】PoyoLab GirlsEdition 30pose",
    "【無料 | FREE】Nizi Pose Set（10種類）",
    "【無料】MFpose-animation V1 55種",
    "【VRChat】椅子になれるツール [MA対応]",
    "【🎁無料】【まめふれんず】もちほぺ！+オマケ、ぽよぽよ瞬きアニメーション（まめきぷ＋リルレオ対応）",
    "【無料版あり】Komano Shapekey+【MA対応】",
    "I字バランスanimation2種",
    "はっぴはっぴロコモーション",
    "【無料有/＋Free sample】Pose Animation Set 5【50種】",
    "キプキプ共鳴+α ギミック【4アバター対応】",
    "【7アバター対応】 🌇The City Strut Pose ✨",
    "ファッション撮影用ポーズ集【234種類】",
    "[VRChat用]メニューいらず！３点トラッキング用自動検知寝返りギミック",
    "【キプフェル専用】尻尾掴み反応アニメーション【VRChat】",
    "【32アバター対応】指ハートハンドジェスチャー+握り具合調整するやつ！【MA対応】",
    "【無料】VRChat用DIVEポーズ２０個",
    "【マリシア】ぴこぴこアニメーション　ミミとシッポが動き出す！【Marycia】",
    "Terrors of Nowhere Emote Bundle",
    "「キプフェル」(Kipfel) Face Tracking Addon",
    "姿勢変更ギミック for デスクトップ【VRChat】",
    "VRChat Avatars3.0向けホバー移動モーション+α(無料/CC0)",
    "【無料】 Motion Pack for Selestia",
    "【 VRChat想定 】ディスプレイのウィング【アニメーション付き】",
    "💎MA対応💎 birdcage AFK for Manuka",
  ]),
  __world__: Object.freeze([
    "LuraSwitch2",
    "【無料】VRC向けワールドプレハブ「10x10x10m」【Unity2022対応】",
    "[VRCワールド] Visitors Information Board [無料]",
    "RBS SleepKit 2 - ベッドギミックこれだけでOK！多機能タブレット搭載【セーブ対応】",
    "【無料】3Dモデル [棚セット]-全12種類三色",
    "【フェード暗転】やさしいテレポート【VRCSDK3 / U#】",
    "Skybox用星空シェーダー「AySkybox_StarrySky」",
    "【無料】VR睡眠用ベッドミラーギミック BedMirror",
    "【VRChatワールドギミック】FlipCamera",
    "【無料】おしゃれなモダンハウス",
    "Simple VRChat Room",
    "【無料】ドアテレポートシステム【VCC対応】",
    "【無料】入退室サウンドシステム【VCC対応】",
    "VRChat向け家具セット(３)",
    "VRChat向け家具セット(２)",
    "【無料】3Dモデル [バー向けセット]",
    "軽量雨粒シェーダー / RainDropShader",
    "【無料ワールド】Slanted Ceiling Room",
    "【特殊3Dモデル】自動サイズ調整額縁",
    "StreamWater 水面シェーダー",
    "ワールド用音楽再生プレイヤーセット【SDK2／SDK3】",
    "【無料】フォトフレーム 同期対応スライドショー機能付き",
    "VRChat向け家具セット(４)",
    "【無料版あり】VRC向けワールドプレハブ「六角形のおうちキット」",
    "VRChat向け家具セット(１)",
    "【無料】nekoVATカーテン（動くよ！）【2周年】",
    "【無料ワールド】FreeRoom",
    "【無料】3Dモデル [ローテーブルセット]-全5種類",
    "【無料】開閉式ブラインド＆カーテン【VRChat用ギミック SDK3】",
    "モダンなインテリア/家具 セット 【Modern Interior Furniture】",
    "Asset List Maker【アセットリスト自動生成ツール】",
    "コースティクスプロジェクターシェーダー / Caustics Projector Shader",
    "Free VRChat Room (Tutorial World)",
    "Noriben AQUARIUM（魚パーティクルと餌やり機能付きアクアリウムセット）",
    "【無料/Free】VRC ワールド  Driftwood Cabin",
    "【Udonギミック】逆首輪ギミック（プレイヤーに引っ張られる首輪）【VRChat】",
    "Re:OCEAN VIEW 【PC / Android（クエスト）対応　ホームワールド】",
    "ビームライトシェーダー / BeamLightShader",
    "【無料】La Fille Green Set",
    "【無料】3Dモデル [ベッドセット]-全6種類",
    "【ワールド パーツ販売】針葉樹フィールド",
    "【VRCワールド】スチームパンクアパートメント　Sサイズ(家具無し)",
    "VRChat想定 カーテン用シェーダー「AyStandard_Curtain」",
    "【VRC向けワールド】木洩れ日の家-Komorebi no ie-",
    "LEDパネルシェーダー / LED Panel Shader",
    "【無料】シンプル家具セット Vol.1 FFP-01【VRC向け3Dモデル】",
    "Quest対応ベーシックウォーターシェーダー / QuestBasicWaterShader",
    "雨の波紋つき置くだけ水たまりシェーダー / Rain Puddle Shader",
    "【販売ワールド】Luminous Hotel【PCVR／Quest】",
    "【無料】オブジェクトリセットギミック",
    "FREE Modern Ocean Side World",
    "【VRC向けワールド/Quest対応】和空間 ～Wakuukan～",
    "Star light",
    "Single Bedroom Free VRChat World",
    "Photo Clip ×30",
    "【販売ワールド】Abstract:Coast【PCVR／Quest】",
    "[VRChat ワールド] Room 8",
    "【無料】3Dモデル [ソファーセット]-全4種類",
    "【8K HDR】JAPANCITY SKYBOX【VRChat】",
    "Vrchat——聖なる光、片光、Light",
    "『heroicons for Lura's Swtich』  Lura's Swtich 用追加アイコン",
    "エフェクトセット 「雨、雪、風、雪虫」",
    "【VRChat想定】古民家 町家 / Japanese Traditional House",
    "駐車場でよく見るやたら足の速い鳥【VRChatワールド用ギミック】",
    "【無料】VRCで動く時計（UnityPackage）",
    "【VRC向けワールド】Dreamlight Home",
    "【VRChatワールドギミック】UnyStylus",
    "スタンドライトセット",
    "シンプルコースティクスプロジェクター / Simple Caustics Projector",
    "【VRC向け無料ワールドギミック】寝落ち者救済バット",
    "【Skybox】Neon city｜ネオンシティスカイボックス",
    "波打ち際シェーダー「nmSeashore」＆ワールドギミックセット",
    "Day Night Cycle UdonSharp (VRChat Prefab)",
    "【無料/VRChatワールド用】訪問者記録ボード (VCC対応)",
    "[遠景用]鳥パーティクル / Bird particle",
    "【販売ワールド】VirtualComfortRoom:Edge",
    "【無料DL3Dモデル】IRREGULARS洋酒セット",
    "【CC0】4K HDR SKYBOX for Unity 2019（24種類）",
    "雲海シェーダー　Sea of Cloud Shader",
    "VRChat向け　ダイニングテーブルセット",
    "【VRChat想定】桜の木、揺れるシェーダー、花びらパーティクル付き(9点)",
    "【自然物アセット】Nature Assets",
    "【無料】シンプルナイトモード(Quest対応)",
    "ワールドつく～る（VRChatワールド制作・アシストツール）",
    "【Free】無料 国産おかき【VRChatワールドギミック】UDON",
    "CQ_Books_3rd",
    "【VRChat ワールド用】アバターフィギュア表示ギミック",
    "【販売ワールド】Gaming Hideout",
    "レーザーライトシェーダー / LaserLightShader",
    "VRC_Starter Kit SDK3 (UdonSharp版)",
    "【Free/無料】プレイヤー視点共有ギミック「ViewTracker」",
    "【VRChat想定】監視カメラシステム【無料】",
    "[無料]桜パーティクル",
    "【VRC Udonギミック】VRC Darts",
    "[VRChat ワールド] Room 10",
    "水槽001",
    "VRChat Bowling Game Prefab VRC",
    "寝台特急個室:A Royal　ホームキット【VRChat想定】",
    "【VRCギミック】Flek Sit ver1.1【ワールド用】",
    "【VRChat想定】水槽Barテーブルセット(10点)",
    "Noriben Fireworks（花火パーティクル）",
    "【VRCワールド】サイバーアパートメント　Sサイズ(家具無し)",
    "【Skybox】zrain",
    "沈む･凹む ベッド",
    "[VRChatワールドギミック]天気予報ウィジェット",
    "3Dモデル [Gaming Room]",
    "私の安らぎ | My Resting Place : RE",
    "振り子時計",
    "VRChatお人形あそびシステムEx - VRCDollSetEX",
    "【旧版】VRChatSDK3ワールド用絵描きギミック「UMoffPen」",
    "立体文字のシンプルミラーセット",
    "流れ星パーティクル / Meteor shower particle",
    "ガラスシェーダー&マテリアルセット すりガラスなど18パターン収録",
    "タッチ式タブレット RTab VRChatワールドギミック",
    "【無料 / Free】ミュートエリア / Mute Area",
    "【無料DL3Dモデル】WELCOME BOARD",
    "[ワールド]Cozy Nest 🐤🌊",
    "【自動切換】Smart Mirror【VRCSDK3 / U#】",
    "【販売ワールド】VirtualComfortPlace:Ryokan【SDK2／SDK3】",
    "【VRChat用QvPenスキン】NRQvPen",
  ]),
});
